# Generated by Django 3.0.4 on 2020-03-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='created_at',
        ),
    ]
