# Generated by Django 3.0.4 on 2020-03-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_todoitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
